### ISSUE TITLE
UI Bug Fixes

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr-ui#72]
1. There are not enough refreshes while performing spatial search which results in url state bugs
2. Too many alerts when doing spatial search
3. Logo bug when screen is small (low)

**Comment by jbyrne6** [comment]
@davidcolemanjpl , below listed are the items I have fixed of the list that were deemed top priority by @viviant100. They are deployed to SIT for testing. I am going to make a PR against the release 1.0.0 branch since these are all bug that are essential to get into v1. Let me know if I have the go-ahead to deploy these to UAT for your testing. I will continue to fix the other bugs on this list but let me know what other items you think are absolutely essential for v1.0.0 release.

1. When generating products using map spatial search option (BBOX), various warnings display while scenes are being retrieved / added ("The scenes entered are not available." "Some scenes entered are not available.")
2. 'Configure Products' should not be an option after adding scenes in UI, as this configuration already occurred via Select Scene 'Configure Options' (top of the Customization page in UI)
3. Customization page in UI - user unable to delete Added Scenes. When refreshing the page after added scenes removed/deleted, the deleted scenes re-appear in SWODLR UI
4. Customization page in UI - Map sizing issues. The size of map should remain in place. The Map in UI should not randomly re-size (e.g., after sizing, and navigating through menus, and back to customization page w/ map or when refreshing the page)
5.  'My Data' page in UI: (user only can only view / display 10 rows of generated data in UI) Generated Products Data do not retain in UI (Should pagination or page numbers be Implemented ?)
6. 'Configure Options / Products' page - advanced options 'Scenes to Customize' - User unable to toggle or select all of the row options for UTM Zone Adjust or MGRS Band Adjust

**Comment by jbyrne6** [comment]
@davidcolemanjpl, the bugs listed in the above comment are now deployed to UAT for your testing.

**Comment by davidcolemanjpl** [comment]
SWODLR UI (SIT/UAT) - (v1.0 Pre-Alpha):

note: SWODLR UI (UAT) – AWS raster create workflow executions are still not completing as expected.  User also unable to locate footprint scenes on the map in SWODLR UAT UI (using Spatial Search Options)


@jbyrne6  - Please advise when the remaining v1 issues have all been remediated / deployed.

FYI -  regarding  the items that were recently _fixed_  "...that were deemed top priority...":


1. When generating products using map spatial search option (BBOX), various warnings display while scenes are being retrieved / added ("The scenes entered are not available." "Some scenes entered are not available.")

  * (Only able to retrieve/locate scenes on UI Map  using cps = 7/72/13-15 in SWODLR SIT UI) – The footprint scene retrieval is sometimes intermittent. Performance is sluggish when retrieving the (3) map footprint scenes. The Added scenes 'spinning wheel' continues to load / turn for a while after the respective Scenes have been Successfully added in UI. 

Note: the previous various warnings no longer display in UI - ("The scenes entered are not available." "Some scenes entered are not available.")

2. 'Configure Products' should not be an option after adding scenes in UI, as this configuration already occurred via Select Scene 'Configure Options' (top of the Customization page in UI)    
  *OK - This issue is resolved - the 'Configure Products' screen is no longer in the UI. User must now use the 'Configure Options' screen prior to Generating Products


3. Customization page in UI - user unable to delete Added Scenes. When refreshing the page after added scenes removed/deleted, the deleted scenes re-appear in SWODLR UI  (issue #9 from Ticket 6008)
  * I think this is OK - issue is resolved 
NOTE: This issue (intermittently) occurred today, user was initially unable to properly delete an added scene (used cps = 1/414/23) (I'll continue to monitor this anomaly)


4. Customization page in UI - Map sizing issues. The size of map should remain in place. The Map in UI should not randomly re-size (e.g., after sizing, and navigating through menus, and back to customization page w/ map or when refreshing the page) 

  * Map in UI still has stability issues, E.g. Map re-sizes after a refresh. 
Also noticed, a created BBOX / polygon  disappears from the MAP in UI after navigating to 'My data' page (or 'About' page) and then back to the Customization page


5. 'My Data' page in UI: (user only can only view / display 10 rows of generated data in UI) Generated Products Data do not retain in UI (Should pagination or page numbers be Implemented ?) 
  * Verified that the user only can now view more than 10 rows of generated data on 'My Data' page in UI.  
But, pagination or page numbers should also be implemented. Table sorting and/or page limit may be needed as well (E.g. Show 20 per page, Show 50 per page, Show 100 per page, etc)


6. 'Configure Options / Products' page - advanced options 'Scenes to Customize' - User unable to toggle or select all of the row options for UTM Zone Adjust or MGRS Band Adjust 
  * OK - This issue appears to be currently resolved 

 
7. Tutorial modal does now start when you click the Tutorial navbar button when on certain pages. (issue #17 from Ticket 6008)
  *OK - This issue appears to be currently resolved - User now able to  able to access the Tutorial link from the 'About' window and/or 'MyData' Page. 

Note: the Tutorial modal still has remaining issues to be resolved including:
-Wording enhancements needed (e.g. , 5/17, 6/17, or 12/17)
-The 'Back' function still does not work as expected for certain tutorial pages (try 15/17 or 16/17  then hit Back, then next to see issues)
-After selecting start button on Tutorial, user can click anywhere on UI screen to page through the tutorial. The user does not have to select 'Next' button in the tutorial window to proceed.

**Comment by jbyrne6** [comment]
@davidcolemanjpl , Thank you for your feedback. I will look into 1,3, and 4. Number 5 is a seprate ticket of #71 .

**Comment by jbyrne6** [comment]
For the last bug fix push here is this subset of the UI bug fix list that are deemed essential for version 1.0.0 release. @davidcolemanjpl let me know what items you think should be added to this list as the top priority and essential for function vs nice to have bug fixes that are not essential for the first version.

- [ ] The 'Back' function does not work as expected for tutorial pages (12/18), (16/18). The tutorial crashes/exits. For tutorial page (17/18), try the 'Back' and then 'Next' to see the issue (blank screen displays if navigating back to Customization/About tabs after selecting 'Next; If user selects the MyData page after selecting 'Next', the tutorial window re-appears w/ tutorial page (18/18)))
- [ ]

**Comment by davidcolemanjpl** [comment]
@jbyrne6 
A few of the main / essential for function front-end items for the SWODLR v1.0.0 release include:

_Tutorial modal issues_: The 'Back' function still does not work as expected for certain tutorial modal pages (try 15/17 or 16/17, then hit Back, then 'Next' to see issue(s)).  The SWODLR UI eventually will freeze at a certain point and adds scenes that were NOT entered / selected by user (1/413/120)
After selecting start button on Tutorial, user can click anywhere on UI screen to page through the tutorial. The user does not have to select 'Next' button in the tutorial window to proceed. (swodlr-UI tutorial issues should also be vetted/remediated https://github.com/podaac/swodlr-ui/issues/83)

_The Map in UI re-sizing issues (and BBOX anomalies)_

_The added scene(s) remove/delete issue in swodlr ui_  

_About page in UI: the 'original algorithm' hyperlink triggers an Invalid Key error_ 


**nice to have** - (Firefox and **Safari**) 'My Data' page - table header has formatting issue - missing columns 
**nice to have** - The user currently unable to invoke the 'Unavailable' and 'Available' statuses. Suggest updating the Generated Products Data statuses on MyData page 
**nice to have** - Update needed for MyData page (pagination and sorting capabilities)
**nice to have** - SWODLR title should match on main page in UI (SWOT Level-2 On-demand Raster Generator vs. SWOT On-Demand Level-2 Raster Generator (noted in page footer)
**nice to have** - The 'About SWODLR' hyperlink on main page (footer) non-functional (note: SWODLR UI main page prior to Earthdata Login)

**Comment by jbyrne6** [comment]
@davidcolemanjpl and I decided on the essential tickets for version 1 which are listed below. The rest are nice to have but version 1 can be deployed without them.

- [ ] speed up spatial search load time
- [ ] tutorial back button crashes site
- [ ] spatial search not working in UAT
- [ ] Can’t change adjust of spatial search granules (SIT)

**Comment by davidcolemanjpl** [comment]
Reviewed recent fixes in SWODLR (SIT) UI - **v1.0 Pre-Alpha** 

_speed up spatial search load time_:
Spatial search is a lot faster loading now when retrieving map footprint scenes (7/72/13-15). Noticed that the spinning wheel continues to spin after the "Successfully added scenes!" message displays in UI

_tutorial back button crashes site_:
The tutorial modal bug seems to be okay at this time, and no longer crashes as before.  (note: noticed today an issue where the tutorial fails to initiate after selecting 'Start' button in the tutorial Modal - believe this new issue is related to tutorail modal pages 15-17, and then skipping or exiting tutorial (https://github.com/podaac/swodlr-ui/issues/83)


Note: Another  bug that should also be remediated for v1:
"About page in UI: the 'original algorithm' hyperlink triggers an Invalid Key error"

**Comment by jbyrne6** [comment]
@davidcolemanjpl these fixed are deployed to SIT and UAT for you to test
### Fixes
- [ ] 1. 10 scene granule limit
- [ ] 2. added version numbers to footer and about page (didn't update version history which is still manual)
- [ ] 3. Spinner running too long
- [ ] 4. Map stays at same location after refresh
- [ ] 5. SWOT original algorithm link on about page updated
- [ ] 6. Can re-run tutorial successfully now after fully completing first tutorial
- [ ] 7. Remove about page link in footer when on the login page

**Comment by jbyrne6** [comment]
**Ok not to do list** 
- [ ] Logo bug when screen is small (low)
- [ ] SWODLR title should match on main page in UI (SWOT Level-2 On-demand Raster Generator vs. SWOT On-Demand Level-2 Raster Generator (noted in page footer)
- [ ] Firefox and Safari) 'My Data' page - table header has formatting issue - missing columns. Same issue on 'Customization' page - Added Scenes table - table header also has missing columns
- [ ] (text format issue) About page, Citation section - the simulated raster data landing page hyperlink appears to have a period (.) noted in the link (using chrome browser). The simulated raster data landing page hyperlink appears to have a space included when viewing link using Safari browser.
- [ ] 'MyData' page in UI: user currently Unable to see or invoke the 'Unavailable' and 'Available' statuses. Suggest updating Generated Products Data statuses to be 'Queued', 'Running', 'FAIL', 'COMPLETE' (similar to the statuses listed in Cumulus UI)
- [ ] The newly added 'copy to clipboard' and 'download' icons on 'My Data' page should include add descriptions when hovering over icons (currently, icons only in swodlr-ui SIT UI)
- [ ] Spatial search not working for a very large area
- [ ] Spatial search polygon not saved as a url parameter.
